//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace NotepadEnhanced.Localization {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Strings {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Strings() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("NotepadEnhanced.Localization.Strings", typeof(Strings).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The version you are downloading is in alpha and may be a bit unstable..
        /// </summary>
        internal static string AlphaDownload {
            get {
                return ResourceManager.GetString("AlphaDownload", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Has been changed outside the editor.
        ///Would you like to reload the document?.
        /// </summary>
        internal static string ChangedOutsideEditor {
            get {
                return ResourceManager.GetString("ChangedOutsideEditor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Exit.
        /// </summary>
        internal static string CmsiExitText {
            get {
                return ResourceManager.GetString("CmsiExitText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Show.
        /// </summary>
        internal static string CmsiShowText {
            get {
                return ResourceManager.GetString("CmsiShowText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Text|*.txt|Batch|*.bat|Config|*.ini|Web|*.html;*.htm;*.css|Source|*.c;*.cpp;*.cs;*.java;*.h|Info|*.inf;*.nfo|All|*.*.
        /// </summary>
        internal static string FilterOpenFile {
            get {
                return ResourceManager.GetString("FilterOpenFile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Text file|*.txt|Other File|*.*.
        /// </summary>
        internal static string FilterSaveFile {
            get {
                return ResourceManager.GetString("FilterSaveFile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Item(s) replaced.
        /// </summary>
        internal static string ItemsReplaced {
            get {
                return ResourceManager.GetString("ItemsReplaced", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please report any typos to the developer.
        /// </summary>
        internal static string LanguageReport {
            get {
                return ResourceManager.GetString("LanguageReport", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Press Ctrl+T to quickly add a blank document.
        /// </summary>
        internal static string MsgAddTabPrompt {
            get {
                return ResourceManager.GetString("MsgAddTabPrompt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Note: The version you are downloading is in beta and may have a few bugs..
        /// </summary>
        internal static string MsgBetaDownload {
            get {
                return ResourceManager.GetString("MsgBetaDownload", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to is a big file,
        ///do you want to open it anyway?.
        /// </summary>
        internal static string MsgBigFile {
            get {
                return ResourceManager.GetString("MsgBigFile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Could not retrieve data from update page!
        ///You can check manually on developers site.
        /// </summary>
        internal static string MsgCoundNotRetrieveData {
            get {
                return ResourceManager.GetString("MsgCoundNotRetrieveData", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Do you really want to permanently delete the active document?.
        /// </summary>
        internal static string MsgDeleteConfirmation {
            get {
                return ResourceManager.GetString("MsgDeleteConfirmation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Could not delete file, the file may be in use elsewhere or you may not have permission to do this..
        /// </summary>
        internal static string MsgDeleteError {
            get {
                return ResourceManager.GetString("MsgDeleteError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Could not navigate to download location.
        /// </summary>
        internal static string MsgDownloadLinkErrorMsg {
            get {
                return ResourceManager.GetString("MsgDownloadLinkErrorMsg", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to A newer version is available, click OK to download..
        /// </summary>
        internal static string MsgNewVersion {
            get {
                return ResourceManager.GetString("MsgNewVersion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No valid printer found!.
        /// </summary>
        internal static string MsgNoPrinter {
            get {
                return ResourceManager.GetString("MsgNoPrinter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Would you like to save changes to &quot;{0}&quot;?.
        /// </summary>
        internal static string MsgSaveFile {
            get {
                return ResourceManager.GetString("MsgSaveFile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unable to find valid update info, sorry for the inconvenience!.
        /// </summary>
        internal static string MsgUpdateInfoError {
            get {
                return ResourceManager.GetString("MsgUpdateInfoError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Your version of {0} is up to date!.
        /// </summary>
        internal static string MsgUpToDate {
            get {
                return ResourceManager.GetString("MsgUpToDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Multiple Documents.
        /// </summary>
        internal static string MultiDocsName {
            get {
                return ResourceManager.GetString("MultiDocsName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to New Text Document.
        /// </summary>
        internal static string NewDoc {
            get {
                return ResourceManager.GetString("NewDoc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No definition found..
        /// </summary>
        internal static string NoDefFound {
            get {
                return ResourceManager.GetString("NoDefFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No file found.
        /// </summary>
        internal static string NoFileFound {
            get {
                return ResourceManager.GetString("NoFileFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please select a refactor profile first.
        /// </summary>
        internal static string NoSelRefactex {
            get {
                return ResourceManager.GetString("NoSelRefactex", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to An error occurred with {0}&apos;s regex pattern.
        /// </summary>
        internal static string RefactexErrorFormat {
            get {
                return ResourceManager.GetString("RefactexErrorFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to For the changes to take effect, the application must restart. 
        ///Would you like to do this now?
        ///
        ///Note: Open documents will be discarded without prompt.
        /// </summary>
        internal static string RestartPrompt {
            get {
                return ResourceManager.GetString("RestartPrompt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Restore Last Session.
        /// </summary>
        internal static string RestoreSessionPrompt {
            get {
                return ResourceManager.GetString("RestoreSessionPrompt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Your settings seemed to be corrupted and were reset..
        /// </summary>
        internal static string SettingsReset {
            get {
                return ResourceManager.GetString("SettingsReset", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Settings have been restored to default.
        /// </summary>
        internal static string SettingsRestored {
            get {
                return ResourceManager.GetString("SettingsRestored", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Undo .
        /// </summary>
        internal static string UndoText {
            get {
                return ResourceManager.GetString("UndoText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unknown.
        /// </summary>
        internal static string Unknown {
            get {
                return ResourceManager.GetString("Unknown", resourceCulture);
            }
        }
    }
}
